### ISSUE TITLE
i18n text not appearing as of 24th June

### ISSUE THREAD

**Issue by jimmythompson** [agoravoting/agora-core-view#9]
We have two clean installs (using the guide on agora/agora-dev-box) of Agora on two machines. Our install from yesterday works fine, but as of today any clean install we do lacks any i18n text.

![screen shot 2015-06-24 at 17 18 15](https://cloud.githubusercontent.com/assets/653864/8335362/145129d0-1a95-11e5-9cbd-85b22a0b9223.png)

The error in the console is as follows:

![screen shot 2015-06-24 at 17 19 01](https://cloud.githubusercontent.com/assets/653864/8335371/221edd78-1a95-11e5-9fa8-521710c094e2.png)

We've tried this using both `master` and `next` and seem to have the same problem. We're unsure if this is a problem with our installs or maybe a package has upgraded, and the `package.json`/`bower.json` is picking up a new version.

**Comment by jimmythompson** [comment]
We tried creating `locales/en-us.json` but this has no effect, seems to default to `en.json` anyway.

**Comment by edulix** [comment]
uhm, we'll have to test ourselves this to see what's the problem, probably something to do with some package being upgraded but who knows

**Comment by jimmythompson** [comment]
Just did a diff of the packages installed.

*NPM*
``` shell
< ├─┬ karma@0.12.36
---
> ├─┬ karma@0.12.37
```

*Bower*
``` shell
< │ └── i18next#1.9.0 (1.10.1 available)
---
> │ └── i18next#1.10.1
```

Would forcing the old version be an okay fix for now?

**Comment by edulix** [comment]
I haven't tested yet, but if you can force it and it works, we wouldn't mind having a patch to force that. I suppose it'll have something to do with the update in the i18next package.
